name: 'Build & push to ECR'
description: 'Builds a docker image and pushes it to ECR'
inputs:
  aws_access_key_id:
    description: "AWS access key ID"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key"
    required: true
  aws_region:
    description: "AWS region"
    required: true
    default: "us-east-1"
  aws_account_id:
    description: "AWS account ID"
    required: true
  ecr_repository_name:
    description: "ECR repository name"
    required: true
  build_directory:
    description: "Directory where the Dockerfile is located"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Define ECR version"
      run: echo "ecr_version=${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:${GITHUB_SHA}" >> $GITHUB_ENV
      shell: bash
    - name: "Define ECR version for latest tag"
      run: echo "ecr_version_latest=${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:latest" >> $GITHUB_ENV
      shell: bash
    - name: "Build image"
      working-directory: ${{ inputs.build_directory }}
      run: docker build -t ${{ env.ecr_version }} -t ${{ env.ecr_version_latest }} .
      shell: bash
    - name: "Dev ECR: login"
      env:
        AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.DEV_AWS_ACCESS_KEY_SECRET }}
      run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com
      shell: bash
    - name: "Dev ECR: tag image"
      run: docker tag ${{ env.ecr_version_latest }} ${{ env.ecr_version }}
      shell: bash
    - name: "Dev ECR: push image"
      run: docker push ${{ env.ecr_version }}
      shell: bash
    - name: "Dev ECR: push latest tag"
      run: docker push ${{ env.ecr_version_latest }}
      shell: bash
