name: 'Build & push to ECR'
description: 'Builds a docker image and pushes it to ECR'
inputs:
  aws_access_key_id:
    description: "AWS access key ID"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key"
    required: true
  aws_region:
    description: "AWS region"
    required: true
    default: "us-east-1"
  aws_account_id:
    description: "AWS account ID"
    required: true
  ecr_repository_name:
    description: "ECR repository name"
    required: true
  build_directory:
    description: "Directory where the Dockerfile is located"
    required: false
  tag:
    description: "Docker image tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Build image"
      working-directory: ${{ inputs.build_directory }}
      run: docker build -t ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:${{ inputs.tag }} -t ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:latest .
      shell: bash
    - name: "Dev ECR: login"
      env:
        AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com
      shell: bash
    - name: "Dev ECR: push ${{ inputs.tag }} tag"
      run: docker push ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:${{ inputs.tag }}
      shell: bash
    - name: "Dev ECR: push latest tag"
      run: docker push ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_name }}:latest
      shell: bash
